// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaD43vl7QJxDmRR5-XmN0z3vov569qy4M',
    appId: '1:884732015669:web:5e7de731bc24d2ff746d7c',
    messagingSenderId: '884732015669',
    projectId: 'fasum-app-2327240063',
    authDomain: 'fasum-app-2327240063.firebaseapp.com',
    databaseURL: 'https://fasum-app-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2327240063.firebasestorage.app',
    measurementId: 'G-8VWC607Z36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpJSdrb2z9za5Hh7Ej9QK-N-ekb7ghNw',
    appId: '1:884732015669:android:fc4d43b0fb59de29746d7c',
    messagingSenderId: '884732015669',
    projectId: 'fasum-app-2327240063',
    databaseURL: 'https://fasum-app-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2327240063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMMBZWZCirkMbLXxL27zcaxf9XH6lxnCU',
    appId: '1:884732015669:ios:e86e506a4fa5951d746d7c',
    messagingSenderId: '884732015669',
    projectId: 'fasum-app-2327240063',
    databaseURL: 'https://fasum-app-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2327240063.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMMBZWZCirkMbLXxL27zcaxf9XH6lxnCU',
    appId: '1:884732015669:ios:e86e506a4fa5951d746d7c',
    messagingSenderId: '884732015669',
    projectId: 'fasum-app-2327240063',
    databaseURL: 'https://fasum-app-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2327240063.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaD43vl7QJxDmRR5-XmN0z3vov569qy4M',
    appId: '1:884732015669:web:a30edb6111a7d675746d7c',
    messagingSenderId: '884732015669',
    projectId: 'fasum-app-2327240063',
    authDomain: 'fasum-app-2327240063.firebaseapp.com',
    databaseURL: 'https://fasum-app-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2327240063.firebasestorage.app',
    measurementId: 'G-PJZ4MSCREG',
  );

}